with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
packages:
  github.com/draftea/payment-system/payments-service/domain:
    interfaces:
      PaymentRepository:
  github.com/draftea/payment-system/shared/events:
    interfaces:
      Publisher: