// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/draftea/payment-system/shared/events"
	mock "github.com/stretchr/testify/mock"

	models "github.com/draftea/payment-system/shared/models"
)

// MockEventStore is an autogenerated mock type for the EventStore type
type MockEventStore struct {
	mock.Mock
}

type MockEventStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStore) EXPECT() *MockEventStore_Expecter {
	return &MockEventStore_Expecter{mock: &_m.Mock}
}

// GetEvents provides a mock function with given fields: ctx, aggregateID
func (_m *MockEventStore) GetEvents(ctx context.Context, aggregateID models.ID) ([]*events.Event, error) {
	ret := _m.Called(ctx, aggregateID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []*events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ID) ([]*events.Event, error)); ok {
		return rf(ctx, aggregateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ID) []*events.Event); ok {
		r0 = rf(ctx, aggregateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ID) error); ok {
		r1 = rf(ctx, aggregateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventStore_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockEventStore_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregateID models.ID
func (_e *MockEventStore_Expecter) GetEvents(ctx interface{}, aggregateID interface{}) *MockEventStore_GetEvents_Call {
	return &MockEventStore_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx, aggregateID)}
}

func (_c *MockEventStore_GetEvents_Call) Run(run func(ctx context.Context, aggregateID models.ID)) *MockEventStore_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ID))
	})
	return _c
}

func (_c *MockEventStore_GetEvents_Call) Return(_a0 []*events.Event, _a1 error) *MockEventStore_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventStore_GetEvents_Call) RunAndReturn(run func(context.Context, models.ID) ([]*events.Event, error)) *MockEventStore_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventsByType provides a mock function with given fields: ctx, eventType, offset, limit
func (_m *MockEventStore) GetEventsByType(ctx context.Context, eventType string, offset int, limit int) ([]*events.Event, error) {
	ret := _m.Called(ctx, eventType, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsByType")
	}

	var r0 []*events.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*events.Event, error)); ok {
		return rf(ctx, eventType, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*events.Event); ok {
		r0 = rf(ctx, eventType, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*events.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, eventType, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEventStore_GetEventsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventsByType'
type MockEventStore_GetEventsByType_Call struct {
	*mock.Call
}

// GetEventsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - eventType string
//   - offset int
//   - limit int
func (_e *MockEventStore_Expecter) GetEventsByType(ctx interface{}, eventType interface{}, offset interface{}, limit interface{}) *MockEventStore_GetEventsByType_Call {
	return &MockEventStore_GetEventsByType_Call{Call: _e.mock.On("GetEventsByType", ctx, eventType, offset, limit)}
}

func (_c *MockEventStore_GetEventsByType_Call) Run(run func(ctx context.Context, eventType string, offset int, limit int)) *MockEventStore_GetEventsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockEventStore_GetEventsByType_Call) Return(_a0 []*events.Event, _a1 error) *MockEventStore_GetEventsByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventStore_GetEventsByType_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*events.Event, error)) *MockEventStore_GetEventsByType_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEvents provides a mock function with given fields: ctx, aggregateID, _a2, expectedVersion
func (_m *MockEventStore) SaveEvents(ctx context.Context, aggregateID models.ID, _a2 []*events.Event, expectedVersion int) error {
	ret := _m.Called(ctx, aggregateID, _a2, expectedVersion)

	if len(ret) == 0 {
		panic("no return value specified for SaveEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ID, []*events.Event, int) error); ok {
		r0 = rf(ctx, aggregateID, _a2, expectedVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventStore_SaveEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEvents'
type MockEventStore_SaveEvents_Call struct {
	*mock.Call
}

// SaveEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregateID models.ID
//   - _a2 []*events.Event
//   - expectedVersion int
func (_e *MockEventStore_Expecter) SaveEvents(ctx interface{}, aggregateID interface{}, _a2 interface{}, expectedVersion interface{}) *MockEventStore_SaveEvents_Call {
	return &MockEventStore_SaveEvents_Call{Call: _e.mock.On("SaveEvents", ctx, aggregateID, _a2, expectedVersion)}
}

func (_c *MockEventStore_SaveEvents_Call) Run(run func(ctx context.Context, aggregateID models.ID, _a2 []*events.Event, expectedVersion int)) *MockEventStore_SaveEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ID), args[2].([]*events.Event), args[3].(int))
	})
	return _c
}

func (_c *MockEventStore_SaveEvents_Call) Return(_a0 error) *MockEventStore_SaveEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventStore_SaveEvents_Call) RunAndReturn(run func(context.Context, models.ID, []*events.Event, int) error) *MockEventStore_SaveEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventStore creates a new instance of MockEventStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStore {
	mock := &MockEventStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
